version: "3"
services:
  api:
    container_name: api-container
    image: node:20.11.1
    working_dir: /usr/src/app
    restart: always
    command: bash -c "npm ci --production && node dist/src/index.js"
    environment:
      - PORT=3000
    volumes:
      - ./dist/:/usr/src/app/dist/
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
    ports:
      - "3000:3000"
